# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.3.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.3.9/cli_Darwin_x86_64.tar.gz"
      sha256 "f98195bf2cd79e8b7e57d00558489b9723d4abd02845488e47188ec15287422d"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.3.9/cli_Darwin_arm64.tar.gz"
      sha256 "828701785ca745d40a90c4c458e80d372e251d2aa3a9e2a55c76068473104e9c"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/cli/releases/download/v0.3.9/cli_Linux_x86_64.tar.gz"
        sha256 "b9d207a20e59b8898e510c719a01f5e52eb207c250e709d104ae2be1e87c8a34"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/cli/releases/download/v0.3.9/cli_Linux_arm64.tar.gz"
        sha256 "0a9650a358f4a290801b14ab97ca66f98a9cb1b28ca27ad8680196d0488608b2"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
