# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT060 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.6.0/cli_Darwin_x86_64.tar.gz"
      sha256 "74ff83bcd6274ee5e57c2a9ca91d9682cd5bdbcc7c22955c1b1a8e2f84dd967e"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.6.0/cli_Darwin_arm64.tar.gz"
      sha256 "d36d6d0d43480f84071eebaa84c264379b85eb8c7cf31729f7fb7296680077e5"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.6.0/cli_Linux_x86_64.tar.gz"
      sha256 "53d239d2bc81fad88708a0f1572b2f06f99ddc11018e634d9bb787f7f6b3b0de"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.6.0/cli_Linux_arm64.tar.gz"
      sha256 "f5bdfaa2a8f28aba346f51fafdeca36e6bbdc132ffe1e06d41f32c9a3972763b"
      def install
        bin.install "miru"
      end
    end
  end
end
