# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT030 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.3.0/cli_Darwin_x86_64.tar.gz"
      sha256 "53104e6e6a3e97028cf3935ee0858172d22958ae16a572f6fb00183e685012bc"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.3.0/cli_Darwin_arm64.tar.gz"
      sha256 "0cd887ed5c638eef971e914ccdb49b83dcc2244c39e3c3f74e6841b8a178c5d0"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.3.0/cli_Linux_x86_64.tar.gz"
      sha256 "0bbaca300d3385462de43acb8f6ef384e7e63d0dc6fa0055a79cc06043c07ac1"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.3.0/cli_Linux_arm64.tar.gz"
      sha256 "9ebf05914140ed50fc0cff661c983ecc7874f621ed601d701c0f637d99ee1ea3"
      def install
        bin.install "miru"
      end
    end
  end
end
