# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.4.0/cli_Darwin_x86_64.tar.gz"
      sha256 "6fa44fe2ed5df9945dedabc8f45efa5eec1b486279d7a96be35342dcc7cb8dfe"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.4.0/cli_Darwin_arm64.tar.gz"
      sha256 "34318eb84e2889714cebbf6d8824eba27d75c9962debb1b5969d41805d25299c"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.4.0/cli_Linux_x86_64.tar.gz"
      sha256 "578fbc1d258b46bd13c5ca3387cf33ffaed7681d82f2ab389dfdc93a1cb44366"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.4.0/cli_Linux_arm64.tar.gz"
      sha256 "f5ea7b9a04e1b5611e4faff45e8d9f5a4627d8921e93904cb25666ea45a2d82a"
      def install
        bin.install "miru"
      end
    end
  end
end
