# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.1.1/cli_Darwin_x86_64.tar.gz"
      sha256 "b263e9b189fb3651f380ee79024a4563f73ae8f4d26a0385dbf611a451704b0e"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.1.1/cli_Darwin_arm64.tar.gz"
      sha256 "121f8309e33b009768eb60162e975db1aa90d5e878e787f9fe34a372b027e58b"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/cli/releases/download/v0.1.1/cli_Linux_x86_64.tar.gz"
        sha256 "0bf02bde58b80714d775b5b5689cebffaeb6427f203719f3f0c106171160d123"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/cli/releases/download/v0.1.1/cli_Linux_arm64.tar.gz"
        sha256 "bd367c2d81d335b896a895704dabb6b89fb0c6230258b79c0fc122349eb8a812"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
