# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT0 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.6.0/cli_Darwin_x86_64.tar.gz"
      sha256 "a776d5bc978ed0499cc69269629c3fce58c658dfd7976f367cc538187f2302c2"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.6.0/cli_Darwin_arm64.tar.gz"
      sha256 "75bf9987373c85992075ad67d666c2e1f42e95a208b02ff2385c017f9e86eff2"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.6.0/cli_Linux_x86_64.tar.gz"
      sha256 "91751b89e85954b02b6096bba7cf697b5f6eb24894e7044fcb8178c34870d370"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.6.0/cli_Linux_arm64.tar.gz"
      sha256 "407d8e8bcd2d5d8ecbc5326f55ab8ace0965c90f25d96cb62a4108c2526a84d5"
      def install
        bin.install "miru"
      end
    end
  end
end
