# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT042 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.4.2/cli_Darwin_x86_64.tar.gz"
      sha256 "6febf3a6e4d6cc0b56680559a6617b7d310512097634ddd15262b71e9abd06c0"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.4.2/cli_Darwin_arm64.tar.gz"
      sha256 "7a4eea59d4aeb092701809cb620a0e5e0c93f8f6aaa53733865ed1e39d0747d6"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.4.2/cli_Linux_x86_64.tar.gz"
      sha256 "ce4e8103927037d8c0ff99050435e8215039760ad7c18a3821bbf6560ccb2510"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.4.2/cli_Linux_arm64.tar.gz"
      sha256 "ce7eb90820f02f0de5f618a060a730a62b12ca83ad147a96bfb3f0d173af29bc"
      def install
        bin.install "miru"
      end
    end
  end
end
