# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.2.0/cli_Darwin_x86_64.tar.gz"
      sha256 "a25165902e84c1d9f6fb23ea7d78d814ca51f9a881e051929a3f33bb34046616"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.2.0/cli_Darwin_arm64.tar.gz"
      sha256 "09e3be8e4b656a08df1c9aa5b763439bf850566a5ff41e4787ef0381fc446ec1"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/cli/releases/download/v0.2.0/cli_Linux_x86_64.tar.gz"
        sha256 "0fc86ba3d9d99c8874da0d65622e6e118e0896432b42d42c131c79bc9e0466dd"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/miruml/cli/releases/download/v0.2.0/cli_Linux_arm64.tar.gz"
        sha256 "15670f3bf48ba5647fab5c47532dc2d42b62ea9a9bc0f8c26c52d2aad9b14c5f"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
