# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MiruAT041 < Formula
  desc "Configuration management for Robotics"
  homepage "https://docs.miruml.com"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/miruml/cli/releases/download/v0.4.1/cli_Darwin_x86_64.tar.gz"
      sha256 "d05f78a94a89ba9f9a33ca60ba5e262eed636ce452f1946c7b2771c331b7e1a3"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/miruml/cli/releases/download/v0.4.1/cli_Darwin_arm64.tar.gz"
      sha256 "5551b1dba2c3169668776903c9cd004d9f07949a75623a7fe7475f8856679538"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.4.1/cli_Linux_x86_64.tar.gz"
      sha256 "e232f6a2963e934d4d62b61de76226df8c02921448fb46196763c94d095b03f1"
      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/miruml/cli/releases/download/v0.4.1/cli_Linux_arm64.tar.gz"
      sha256 "90b1d63f3969d1d998ed52824aa3b0a09b493e92101bdd80e2bff878dc5426a4"
      def install
        bin.install "miru"
      end
    end
  end
end
